/**
 * PDF Export Utility
 * Generate PDF reports for scan results using pdf-lib
 */

import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'

interface ScanReportData {
  url: string
  domain: string
  score: number
  label: string
  reasons: string[]
  aiConfidence: number
  scannedAt: string
}

/**
 * Generate a PDF scan report
 */
export async function generateScanReport(data: ScanReportData): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create()
  const page = pdfDoc.addPage([595, 842]) // A4
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  const { width, height } = page.getSize()
  let y = height - 50

  // Title
  page.drawText('ANTI-SCAM - Scan Report', {
    x: 50,
    y,
    size: 24,
    font: boldFont,
    color: rgb(0.1, 0.1, 0.3),
  })
  y -= 40

  // Divider line
  page.drawLine({
    start: { x: 50, y },
    end: { x: width - 50, y },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  })
  y -= 30

  // URL info
  page.drawText('URL:', { x: 50, y, size: 12, font: boldFont, color: rgb(0.3, 0.3, 0.3) })
  page.drawText(data.url, { x: 120, y, size: 12, font, color: rgb(0, 0, 0) })
  y -= 25

  page.drawText('Domain:', { x: 50, y, size: 12, font: boldFont, color: rgb(0.3, 0.3, 0.3) })
  page.drawText(data.domain, { x: 120, y, size: 12, font, color: rgb(0, 0, 0) })
  y -= 25

  page.drawText('Score:', { x: 50, y, size: 12, font: boldFont, color: rgb(0.3, 0.3, 0.3) })
  const scoreColor = data.score <= 30 ? rgb(0.06, 0.73, 0.51) : data.score <= 60 ? rgb(0.96, 0.62, 0.04) : rgb(0.94, 0.27, 0.27)
  page.drawText(`${data.score}/100 (${data.label})`, { x: 120, y, size: 14, font: boldFont, color: scoreColor })
  y -= 25

  page.drawText('AI Confidence:', { x: 50, y, size: 12, font: boldFont, color: rgb(0.3, 0.3, 0.3) })
  page.drawText(`${(data.aiConfidence * 100).toFixed(1)}%`, { x: 150, y, size: 12, font, color: rgb(0, 0, 0) })
  y -= 25

  page.drawText('Scanned at:', { x: 50, y, size: 12, font: boldFont, color: rgb(0.3, 0.3, 0.3) })
  page.drawText(data.scannedAt, { x: 150, y, size: 12, font, color: rgb(0, 0, 0) })
  y -= 40

  // Reasons
  page.drawText('Analysis Details:', { x: 50, y, size: 14, font: boldFont, color: rgb(0.1, 0.1, 0.3) })
  y -= 25

  for (const reason of data.reasons) {
    if (y < 50) break
    page.drawText(`• ${reason}`, { x: 60, y, size: 11, font, color: rgb(0.2, 0.2, 0.2) })
    y -= 20
  }

  // Footer
  page.drawText('Generated by Anti-Scam Platform - https://antiscam.vn', {
    x: 50,
    y: 30,
    size: 9,
    font,
    color: rgb(0.6, 0.6, 0.6),
  })

  return pdfDoc.save()
}

/**
 * Download a PDF in the browser
 */
export function downloadPDF(pdfBytes: Uint8Array, filename: string = 'scan-report.pdf') {
  const blob = new Blob([pdfBytes], { type: 'application/pdf' })
  const link = document.createElement('a')
  link.href = URL.createObjectURL(blob)
  link.download = filename
  link.click()
  URL.revokeObjectURL(link.href)
}
