/**
 * PDF Export API
 */

import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/app/lib/auth'
import prisma from '@/app/lib/db'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'
export async function GET(
  request: NextRequest,
  { params }: { params: { scanId: string } }
) {
  try {
    const session = await getServerSession(authOptions)

    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // PDF export is Business+ only
    if (session.user.tier === 'FREE' || session.user.tier === 'PRO') {
      return NextResponse.json(
        { error: 'PDF export chỉ dành cho gói Business trở lên' },
        { status: 403 }
      )
    }

    const { scanId } = params

    const scan = await prisma.scanHistory.findUnique({
      where: { id: scanId },
    })

    if (!scan || scan.userId !== session.user.id) {
      return NextResponse.json(
        { error: 'Scan not found or unauthorized' },
        { status: 404 }
      )
    }

    // Create PDF
    const pdfDoc = await PDFDocument.create()
    const page = pdfDoc.addPage([595.28, 841.89]) // A4 size
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

    const { width, height } = page.getSize()
    let yPosition = height - 50

    // Title
    page.drawText('ANTISCAM - Scan Report', {
      x: 50,
      y: yPosition,
      size: 24,
      font: boldFont,
      color: rgb(0, 0.4, 0.8),
    })
    yPosition -= 40

    // URL
    page.drawText('URL Scanned:', {
      x: 50,
      y: yPosition,
      size: 12,
      font: boldFont,
    })
    yPosition -= 20
    page.drawText(scan.url, {
      x: 50,
      y: yPosition,
      size: 10,
      font,
      color: rgb(0.2, 0.2, 0.2),
    })
    yPosition -= 30

    // Risk Level (based on label)
    const labelColors: Record<string, [number, number, number]> = {
      'safe': [0, 0.7, 0],
      'low_risk': [0.5, 0.8, 0],
      'suspicious': [1, 0.6, 0],
      'dangerous': [1, 0, 0],
      'scam': [0.8, 0, 0],
    }
    const [r, g, b] = labelColors[scan.label.toLowerCase()] || [0.5, 0.5, 0.5]
    const riskColor = rgb(r, g, b)

    page.drawText('Classification:', {
      x: 50,
      y: yPosition,
      size: 12,
      font: boldFont,
    })
    page.drawText(scan.label.toUpperCase(), {
      x: 150,
      y: yPosition,
      size: 14,
      font: boldFont,
      color: riskColor,
    })
    yPosition -= 30

    // Risk Score
    page.drawText(`Risk Score: ${scan.score}/100`, {
      x: 50,
      y: yPosition,
      size: 12,
      font,
    })
    yPosition -= 30

    // Reasons
    if (scan.reasons && scan.reasons.length > 0) {
      page.drawText('Flags Detected:', {
        x: 50,
        y: yPosition,
        size: 12,
        font: boldFont,
      })
      yPosition -= 20

      scan.reasons.forEach((reason) => {
        if (yPosition < 100) {
          const newPage = pdfDoc.addPage([595.28, 841.89])
          yPosition = height - 50
        }
        page.drawText(`• ${reason}`, {
          x: 70,
          y: yPosition,
          size: 10,
          font,
        })
        yPosition -= 18
      })
    }

    // Scan date
    yPosition -= 20
    page.drawText(`Scanned at: ${new Date(scan.createdAt).toLocaleString('vi-VN')}`, {
      x: 50,
      y: yPosition,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    })

    // Footer
    page.drawText('Generated by ANTISCAM - https://antiscam.vn', {
      x: 50,
      y: 30,
      size: 8,
      font,
      color: rgb(0.5, 0.5, 0.5),
    })

    const pdfBytes = await pdfDoc.save()

    return new NextResponse(Buffer.from(pdfBytes), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="antiscam-report-${scanId}.pdf"`,
      },
    })

  } catch (error) {
    console.error('PDF export error:', error)
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    )
  }
}
