$ErrorActionPreference = "Continue"
Set-Location "d:\ANTISCAM"

$commitMap = @{
    "types/api.ts"                              = "feat: add API request and response type definitions"
    "types/user.ts"                             = "feat: add user-related type definitions"
    "types/scan.ts"                             = "feat: add scan result type definitions"
    "types/report.ts"                           = "feat: add report type definitions"
    "types/quiz.ts"                             = "feat: add quiz type definitions"
    "types/campaign.ts"                         = "feat: add campaign type definitions"
    "types/organization.ts"                     = "feat: add organization type definitions"
    "types/notification.ts"                     = "feat: add notification type definitions"
    "types/blog.ts"                             = "feat: add blog type definitions"
    "types/analytics.ts"                        = "feat: add analytics event type definitions"
    "types/tools.ts"                            = "feat: add tool result type definitions"
    "types/common.ts"                           = "feat: add common shared type definitions"
    "types/extension.ts"                        = "feat: add browser extension type definitions"
    "types/index.ts"                            = "feat: add types barrel export file"
    "types/guards.ts"                           = "feat: add type guard utility functions"
    "app/lib/validations/scanSchema.ts"         = "feat: add Zod scan validation schemas"
    "app/lib/validations/reportSchema.ts"       = "feat: add Zod report validation schemas"
    "app/lib/validations/userSchema.ts"         = "feat: add Zod user validation schemas"
    "app/lib/validations/contactSchema.ts"      = "feat: add Zod contact form validation schema"
    "app/lib/validations/quizSchema.ts"         = "feat: add Zod quiz validation schemas"
    "app/lib/validations/apiKeySchema.ts"       = "feat: add Zod API key validation schemas"
    "app/lib/validations/organizationSchema.ts" = "feat: add Zod organization validation schemas"
    "app/lib/validations/watchlistSchema.ts"    = "feat: add Zod watchlist validation schemas"
    "app/lib/validations/campaignSchema.ts"     = "feat: add Zod campaign validation schemas"
    "app/lib/validations/blogSchema.ts"         = "feat: add Zod blog post validation schemas"
    "app/lib/validations/searchSchema.ts"       = "feat: add Zod search validation schema"
    "app/lib/validations/feedbackSchema.ts"     = "feat: add Zod feedback validation schema"
    "app/lib/validations/newsletterSchema.ts"   = "feat: add Zod newsletter validation schema"
    "app/lib/validations/alertSchema.ts"        = "feat: add Zod scam alert validation schema"
    "app/lib/validations/index.ts"              = "feat: add validations barrel export file"
    "app/api/contact/route.ts"                  = "feat: add contact form API endpoint"
    "app/api/newsletter/route.ts"               = "feat: add newsletter subscription API endpoint"
    "app/api/feedback/route.ts"                 = "feat: add user feedback API endpoint"
    "app/api/health/route.ts"                   = "feat: add health check API endpoint"
    "app/api/version/route.ts"                  = "feat: add app version API endpoint"
    "app/api/campaigns/route.ts"                = "feat: add campaigns listing API endpoint"
    "app/api/leaderboard/route.ts"              = "feat: add community leaderboard API endpoint"
    "app/api/resources/route.ts"                = "feat: add downloadable resources API endpoint"
    "app/api/blog/route.ts"                     = "feat: add blog posts listing API endpoint"
    "app/api/notifications/route.ts"            = "feat: add notifications API endpoint"
    "app/api/user/settings/route.ts"            = "feat: add user settings API endpoint"
    "app/api/user/profile/route.ts"             = "feat: add user profile API endpoint"
    "app/api/user/security/route.ts"            = "feat: add user security API endpoint"
    "app/api/phone-check/route.ts"              = "feat: add phone number scam check API endpoint"
    "app/api/ip-lookup/route.ts"                = "feat: add IP lookup API endpoint"
    "app/api/whois/route.ts"                    = "feat: add WHOIS lookup API endpoint"
    "app/api/analytics/events/route.ts"         = "feat: add analytics events tracking API endpoint"
    "app/api/admin/users/route.ts"              = "feat: add admin user management API endpoint"
    "app/api/admin/reports/route.ts"            = "feat: add admin report management API endpoint"
    "app/api/admin/alerts/route.ts"             = "feat: add admin scam alerts CRUD API endpoint"
    "app/api/search/route.ts"                   = "feat: add global search API endpoint"
    "app/api/admin/stats/route.ts"              = "feat: add admin dashboard statistics API endpoint"
    "app/api/admin/blocklist/route.ts"          = "feat: add admin blocklist management API endpoint"
    "app/api/admin/whitelist/route.ts"          = "feat: add admin whitelist management API endpoint"
    "app/api/email-check/route.ts"              = "feat: add email scam check API endpoint"
    "app/lib/notifications.ts"                  = "feat: add notification service module"
    "app/lib/emailService.ts"                   = "feat: add email service with templates"
    "app/lib/cacheService.ts"                   = "feat: add in-memory cache service with TTL"
    "app/lib/analyticsService.ts"               = "feat: add client-side analytics tracking service"
    "app/lib/searchService.ts"                  = "feat: add global search service"
    "app/lib/seoUtils.ts"                       = "feat: add SEO utility functions for meta tags"
    "app/lib/permissionService.ts"              = "feat: add role-based permission service"
    "app/lib/rateLimitService.ts"               = "feat: add tier-based rate limit service"
    "app/lib/exportService.ts"                  = "feat: add data export service for JSON and text"
    "app/lib/websocketService.ts"               = "feat: add WebSocket service with auto-reconnect"
    ".github/workflows/ci.yml"                  = "ci: add GitHub Actions CI workflow"
    ".github/workflows/deploy.yml"              = "ci: add Vercel deployment workflow"
    ".github/workflows/security.yml"            = "ci: add weekly security audit workflow"
    ".github/workflows/codeql.yml"              = "ci: add CodeQL security analysis workflow"
    ".github/dependabot.yml"                    = "ci: add Dependabot configuration"
    ".github/ISSUE_TEMPLATE/bug_report.md"      = "docs: add bug report issue template"
    ".github/ISSUE_TEMPLATE/feature_request.md" = "docs: add feature request issue template"
    ".github/pull_request_template.md"          = "docs: add pull request template"
    ".github/CODEOWNERS"                        = "ci: add CODEOWNERS file"
    ".github/FUNDING.yml"                       = "ci: add GitHub funding configuration"
    "docs/API.md"                               = "docs: add comprehensive API documentation"
    "docs/ARCHITECTURE.md"                      = "docs: add architecture overview document"
    "docs/DEPLOYMENT.md"                        = "docs: add deployment guide"
    "docs/CONTRIBUTING.md"                      = "docs: add contributing guidelines"
    "docs/SECURITY.md"                          = "docs: add security policy document"
    "docs/CHANGELOG.md"                         = "docs: add changelog with version history"
    "docs/DATABASE.md"                          = "docs: add database schema documentation"
    "docs/TESTING.md"                           = "docs: add testing guide"
    "docs/EXTENSION.md"                         = "docs: add browser extension development guide"
    "docs/QUIZ_SYSTEM.md"                       = "docs: add quiz system documentation"
    "docs/SCAN_ENGINE.md"                       = "docs: add scan engine technical documentation"
    "docs/PAYMENT.md"                           = "docs: add payment integration documentation"
    "docs/I18N.md"                              = "docs: add internationalization guide"
    "docs/MONITORING.md"                        = "docs: add monitoring and observability guide"
    "docs/PRIVACY.md"                           = "docs: add privacy policy document"
    "docs/TERMS.md"                             = "docs: add terms of service document"
    "docs/GLOSSARY.md"                          = "docs: add glossary of security terms"
    "docs/ROADMAP.md"                           = "docs: add product roadmap"
    "docs/FAQ_CONTENT.md"                       = "docs: add FAQ content document"
    "app/lib/config.ts"                         = "feat: add centralized application configuration"
    "app/lib/constants/riskLevels.ts"           = "feat: add risk level constants"
    "app/lib/constants/scamCategories.ts"       = "feat: add scam category constants"
    "app/lib/constants/tiers.ts"                = "feat: add subscription tier constants"
    "app/lib/constants/navigation.ts"           = "feat: add navigation constants"
    "app/lib/constants/seo.ts"                  = "feat: add SEO default constants"
    "app/lib/constants/errorMessages.ts"        = "feat: add error message constants"
    "app/lib/constants/regex.ts"                = "feat: add regex pattern constants"
    "app/lib/constants/index.ts"                = "feat: add constants barrel export"
    ".editorconfig"                             = "chore: add EditorConfig"
    ".prettierrc"                               = "chore: add Prettier configuration"
    ".prettierignore"                           = "chore: add Prettier ignore"
    "app/lib/env.ts"                            = "feat: add environment variable validation"
    ".nvmrc"                                    = "chore: add Node.js version specification"
    ".dockerignore"                             = "chore: add Docker ignore"
    "Dockerfile"                                = "chore: add Dockerfile for containerized deployment"
    "docker-compose.yml"                        = "chore: add Docker Compose for local development"
    "app/not-found.tsx"                         = "feat: add custom 404 not found page"
    "app/loading.tsx"                           = "feat: add global loading component"
    "README.md"                                 = "docs: update README with comprehensive documentation"
}

$count = 0
foreach ($file in $commitMap.Keys) {
    if (Test-Path $file) {
        git add -- $file 2>$null
        git commit -m $commitMap[$file] 2>$null
        $count++
        if ($count % 20 -eq 0) { Write-Host "$count commits done..." }
    }
}

# Also commit modified files
git add app/components/ExtensionBanner.tsx 2>$null
git commit -m "refactor: update ExtensionBanner component styling" 2>$null

# Commit scripts
git add scripts/ 2>$null
git commit -m "chore: add batch commit generation scripts" 2>$null

Write-Host "Total commits: $($count + 2)"
