
# Phase 4: Components
$components = @{
  "Breadcrumbs" = "'use client'`nimport React from 'react'`nimport Link from 'next/link'`n`ninterface BreadcrumbItem { label: string; href?: string }`n`nexport function Breadcrumbs({ items }: { items: BreadcrumbItem[] }) {`n  return (`n    <nav aria-label='Breadcrumb' className='flex items-center gap-2 text-sm text-gray-500'>`n      {items.map((item, i) => (`n        <React.Fragment key={i}>`n          {i > 0 && <span>/</span>}`n          {item.href ? (`n            <Link href={item.href} className='hover:text-blue-500 transition-colors'>{item.label}</Link>`n          ) : (`n            <span className='text-gray-900 dark:text-white font-medium'>{item.label}</span>`n          )}`n        </React.Fragment>`n      ))}`n    </nav>`n  )`n}"
  "Stepper" = "'use client'`n`nexport function Stepper({ steps, current }: { steps: string[]; current: number }) {`n  return (`n    <div className='flex items-center gap-4'>`n      {steps.map((step, i) => (`n        <div key={i} className='flex items-center gap-2'>`n          <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold `+`n            (i <= current ? 'bg-blue-500 text-white' : 'bg-gray-200 text-gray-500')}>`n            {i < current ? '\u2713' : i + 1}`n          </div>`n          <span className={i <= current ? 'font-medium' : 'text-gray-400'}>{step}</span>`n          {i < steps.length - 1 && <div className='w-8 h-px bg-gray-300' />}`n        </div>`n      ))}`n    </div>`n  )`n}"
  "Drawer" = "'use client'`nimport { useEffect } from 'react'`n`nexport function Drawer({ open, onClose, children, side = 'right' }: { open: boolean; onClose: () => void; children: React.ReactNode; side?: 'left' | 'right' }) {`n  useEffect(() => { if (open) document.body.style.overflow = 'hidden'; else document.body.style.overflow = ''; return () => { document.body.style.overflow = '' } }, [open])`n  if (!open) return null`n  return (`n    <div className='fixed inset-0 z-50'>`n      <div className='absolute inset-0 bg-black/50' onClick={onClose} />`n      <div className={`absolute top-0 bottom-0 w-80 bg-white dark:bg-gray-900 shadow-xl p-6 overflow-y-auto transition-transform `+ (side === 'right' ? 'right-0' : 'left-0')}>`n        <button onClick={onClose} className='absolute top-4 right-4 text-gray-400 hover:text-gray-600'>\u2715</button>`n        {children}`n      </div>`n    </div>`n  )`n}"
  "Switch" = "'use client'`n`nexport function Switch({ checked, onChange, label }: { checked: boolean; onChange: (v: boolean) => void; label?: string }) {`n  return (`n    <label className='flex items-center gap-3 cursor-pointer'>`n      <button role='switch' aria-checked={checked} onClick={() => onChange(!checked)}`n        className={`relative w-11 h-6 rounded-full transition-colors `+ (checked ? 'bg-blue-500' : 'bg-gray-300')}>`n        <span className={`absolute top-0.5 left-0.5 w-5 h-5 bg-white rounded-full transition-transform `+ (checked ? 'translate-x-5' : '')} />`n      </button>`n      {label && <span className='text-sm'>{label}</span>}`n    </label>`n  )`n}"
  "Avatar" = "'use client'`n`nexport function Avatar({ src, name, size = 40 }: { src?: string; name: string; size?: number }) {`n  const initials = name.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase()`n  if (src) return <img src={src} alt={name} width={size} height={size} className='rounded-full object-cover' />`n  const colors = ['bg-blue-500','bg-green-500','bg-purple-500','bg-orange-500','bg-pink-500']`n  const color = colors[name.length % colors.length]`n  return <div style={{width:size,height:size}} className={`${color} rounded-full flex items-center justify-center text-white font-bold text-sm`}>{initials}</div>`n}"
  "Divider" = "'use client'`n`nexport function Divider({ label, className = '' }: { label?: string; className?: string }) {`n  if (!label) return <hr className={`border-gray-200 dark:border-gray-700 ${className}`} />`n  return (`n    <div className={`flex items-center gap-4 ${className}`}>`n      <div className='flex-1 h-px bg-gray-200 dark:bg-gray-700' />`n      <span className='text-sm text-gray-400'>{label}</span>`n      <div className='flex-1 h-px bg-gray-200 dark:bg-gray-700' />`n    </div>`n  )`n}"
  "Chip" = "'use client'`n`nexport function Chip({ label, color = 'blue', onRemove }: { label: string; color?: string; onRemove?: () => void }) {`n  const colors: Record<string, string> = { blue: 'bg-blue-100 text-blue-800', green: 'bg-green-100 text-green-800', red: 'bg-red-100 text-red-800', yellow: 'bg-yellow-100 text-yellow-800', gray: 'bg-gray-100 text-gray-800' }`n  return (`n    <span className={`inline-flex items-center gap-1 px-3 py-1 rounded-full text-sm font-medium ${colors[color] || colors.blue}`}>`n      {label}`n      {onRemove && <button onClick={onRemove} className='ml-1 hover:opacity-70'>\u2715</button>}`n    </span>`n  )`n}"
  "Timeline" = "'use client'`n`ninterface TimelineItem { title: string; description?: string; date?: string; icon?: React.ReactNode }`n`nexport function Timeline({ items }: { items: TimelineItem[] }) {`n  return (`n    <div className='space-y-6'>`n      {items.map((item, i) => (`n        <div key={i} className='flex gap-4'>`n          <div className='flex flex-col items-center'>`n            <div className='w-3 h-3 rounded-full bg-blue-500 ring-4 ring-blue-100' />`n            {i < items.length - 1 && <div className='w-0.5 flex-1 bg-gray-200' />}`n          </div>`n          <div className='pb-6'>`n            <h4 className='font-medium'>{item.title}</h4>`n            {item.description && <p className='text-sm text-gray-500 mt-1'>{item.description}</p>}`n            {item.date && <time className='text-xs text-gray-400 mt-1'>{item.date}</time>}`n          </div>`n        </div>`n      ))}`n    </div>`n  )`n}"
  "Pagination" = "'use client'`n`nexport function Pagination({ page, totalPages, onPageChange }: { page: number; totalPages: number; onPageChange: (p: number) => void }) {`n  const pages = Array.from({ length: Math.min(totalPages, 7) }, (_, i) => i + 1)`n  return (`n    <nav className='flex items-center gap-2'>`n      <button onClick={() => onPageChange(Math.max(1, page - 1))} disabled={page === 1} className='px-3 py-1 rounded border disabled:opacity-50'>\u2190</button>`n      {pages.map(p => (`n        <button key={p} onClick={() => onPageChange(p)} className={`px-3 py-1 rounded border `+ (p === page ? 'bg-blue-500 text-white' : 'hover:bg-gray-100')}>{p}</button>`n      ))}`n      <button onClick={() => onPageChange(Math.min(totalPages, page + 1))} disabled={page === totalPages} className='px-3 py-1 rounded border disabled:opacity-50'>\u2192</button>`n    </nav>`n  )`n}"
  "CircularProgress" = "'use client'`n`nexport function CircularProgress({ value, size = 80, strokeWidth = 8, color = '#3B82F6' }: { value: number; size?: number; strokeWidth?: number; color?: string }) {`n  const radius = (size - strokeWidth) / 2`n  const circumference = 2 * Math.PI * radius`n  const offset = circumference - (value / 100) * circumference`n  return (`n    <svg width={size} height={size} className='transform -rotate-90'>`n      <circle cx={size/2} cy={size/2} r={radius} stroke='#E5E7EB' strokeWidth={strokeWidth} fill='none' />`n      <circle cx={size/2} cy={size/2} r={radius} stroke={color} strokeWidth={strokeWidth} fill='none' strokeDasharray={circumference} strokeDashoffset={offset} strokeLinecap='round' className='transition-all duration-500' />`n      <text x='50%' y='50%' textAnchor='middle' dy='.3em' className='transform rotate-90 origin-center fill-current text-sm font-bold'>{Math.round(value)}%</text>`n    </svg>`n  )`n}"
  "StatusIndicator" = "'use client'`n`nexport function StatusIndicator({ status, label }: { status: 'online' | 'offline' | 'busy' | 'away'; label?: string }) {`n  const colors = { online: 'bg-green-500', offline: 'bg-gray-400', busy: 'bg-red-500', away: 'bg-yellow-500' }`n  return (`n    <div className='flex items-center gap-2'>`n      <span className={`w-2.5 h-2.5 rounded-full ${colors[status]} `+ (status === 'online' ? 'animate-pulse' : '')} />`n      {label && <span className='text-sm text-gray-600'>{label}</span>}`n    </div>`n  )`n}"
  "Marquee" = "'use client'`n`nexport function Marquee({ children, speed = 30 }: { children: React.ReactNode; speed?: number }) {`n  return (`n    <div className='overflow-hidden whitespace-nowrap'>`n      <div className='inline-flex animate-marquee' style={{ animationDuration: speed + 's' }}>`n        <div className='flex items-center gap-8'>{children}</div>`n        <div className='flex items-center gap-8 ml-8'>{children}</div>`n      </div>`n    </div>`n  )`n}"
  "ErrorBoundary" = "'use client'`nimport React from 'react'`n`ninterface Props { children: React.ReactNode; fallback?: React.ReactNode }`ninterface State { hasError: boolean; error?: Error }`n`nexport class ErrorBoundary extends React.Component<Props, State> {`n  constructor(props: Props) { super(props); this.state = { hasError: false } }`n  static getDerivedStateFromError(error: Error) { return { hasError: true, error } }`n  componentDidCatch(error: Error, info: React.ErrorInfo) { console.error('ErrorBoundary:', error, info) }`n  render() {`n    if (this.state.hasError) return this.props.fallback || <div className='p-8 text-center'><h2 className='text-xl font-bold text-red-500'>Something went wrong</h2><p className='text-gray-500 mt-2'>{this.state.error?.message}</p><button onClick={() => this.setState({ hasError: false })} className='mt-4 px-4 py-2 bg-blue-500 text-white rounded'>Try Again</button></div>`n    return this.props.children`n  }`n}"
  "BackToTop" = "'use client'`nimport { useState, useEffect } from 'react'`n`nexport function BackToTop() {`n  const [show, setShow] = useState(false)`n  useEffect(() => { const h = () => setShow(window.scrollY > 400); window.addEventListener('scroll', h, { passive: true }); return () => window.removeEventListener('scroll', h) }, [])`n  if (!show) return null`n  return <button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className='fixed bottom-6 right-6 w-12 h-12 bg-blue-500 text-white rounded-full shadow-lg flex items-center justify-center hover:bg-blue-600 transition-all z-50' aria-label='Back to top'>\u2191</button>`n}"
  "CookieConsent" = "'use client'`nimport { useState, useEffect } from 'react'`n`nexport function CookieConsent() {`n  const [show, setShow] = useState(false)`n  useEffect(() => { if (!localStorage.getItem('cookie-consent')) setShow(true) }, [])`n  const accept = () => { localStorage.setItem('cookie-consent', 'true'); setShow(false) }`n  if (!show) return null`n  return (`n    <div className='fixed bottom-0 left-0 right-0 bg-gray-900 text-white p-4 z-50 flex items-center justify-between flex-wrap gap-4'>`n      <p className='text-sm'>Trang web s\u1EED d\u1EE5ng cookie \u0111\u1EC3 c\u1EA3i thi\u1EC7n tr\u1EA3i nghi\u1EC7m. B\u1EB1ng vi\u1EC7c ti\u1EBFp t\u1EE5c, b\u1EA1n \u0111\u1ED3ng y\u0301 v\u1EDBi ch\u00EDnh s\u00E1ch cookie.</p>`n      <div className='flex gap-2'><button onClick={accept} className='px-4 py-2 bg-blue-500 rounded text-sm hover:bg-blue-600'>Ch\u1EA5p nh\u1EADn</button><button onClick={() => setShow(false)} className='px-4 py-2 border border-gray-600 rounded text-sm hover:bg-gray-800'>T\u1EEB ch\u1ED1i</button></div>`n    </div>`n  )`n}"
  "ScrollProgress" = "'use client'`nimport { useState, useEffect } from 'react'`n`nexport function ScrollProgress() {`n  const [progress, setProgress] = useState(0)`n  useEffect(() => { const h = () => { const s = document.documentElement.scrollTop; const t = document.documentElement.scrollHeight - document.documentElement.clientHeight; setProgress(t > 0 ? (s / t) * 100 : 0) }; window.addEventListener('scroll', h, { passive: true }); return () => window.removeEventListener('scroll', h) }, [])`n  return <div className='fixed top-0 left-0 right-0 h-1 z-[60]'><div className='h-full bg-gradient-to-r from-blue-500 to-purple-500 transition-all duration-150' style={{ width: progress + '%' }} /></div>`n}"
  "PricingCard" = "'use client'`n`ninterface PricingProps { name: string; price: string; features: string[]; popular?: boolean; cta?: string }`n`nexport function PricingCard({ name, price, features, popular, cta = 'B\u1EAFt \u0111\u1EA7u' }: PricingProps) {`n  return (`n    <div className={`rounded-2xl p-8 border-2 `+ (popular ? 'border-blue-500 shadow-xl relative' : 'border-gray-200')}>`n      {popular && <span className='absolute -top-3 left-1/2 -translate-x-1/2 bg-blue-500 text-white text-xs px-3 py-1 rounded-full'>Ph\u1ED5 bi\u1EBFn</span>}`n      <h3 className='text-xl font-bold'>{name}</h3>`n      <div className='mt-4'><span className='text-4xl font-bold'>{price}</span><span className='text-gray-500'>/th\u00E1ng</span></div>`n      <ul className='mt-6 space-y-3'>{features.map((f, i) => <li key={i} className='flex items-center gap-2 text-sm'><span className='text-green-500'>\u2713</span>{f}</li>)}</ul>`n      <button className={`w-full mt-8 py-3 rounded-xl font-medium `+ (popular ? 'bg-blue-500 text-white hover:bg-blue-600' : 'bg-gray-100 hover:bg-gray-200')}>{cta}</button>`n    </div>`n  )`n}"
  "FaqAccordion" = "'use client'`nimport { useState } from 'react'`n`ninterface FaqItem { question: string; answer: string }`n`nexport function FaqAccordion({ items }: { items: FaqItem[] }) {`n  const [openIndex, setOpenIndex] = useState<number | null>(null)`n  return (`n    <div className='space-y-3'>`n      {items.map((item, i) => (`n        <div key={i} className='border rounded-xl overflow-hidden'>`n          <button onClick={() => setOpenIndex(openIndex === i ? null : i)} className='w-full px-6 py-4 text-left flex justify-between items-center hover:bg-gray-50'>`n            <span className='font-medium'>{item.question}</span>`n            <span className='text-xl'>{openIndex === i ? '\u2212' : '+'}</span>`n          </button>`n          {openIndex === i && <div className='px-6 pb-4 text-gray-600'>{item.answer}</div>}`n        </div>`n      ))}`n    </div>`n  )`n}"
  "SocialLinks" = "'use client'`n`nexport function SocialLinks({ links }: { links: { platform: string; url: string }[] }) {`n  const icons: Record<string, string> = { facebook: 'FB', twitter: 'TW', github: 'GH', linkedin: 'LI', youtube: 'YT' }`n  return (`n    <div className='flex items-center gap-3'>`n      {links.map((link, i) => (`n        <a key={i} href={link.url} target='_blank' rel='noopener noreferrer' className='w-10 h-10 rounded-full bg-gray-100 dark:bg-gray-800 flex items-center justify-center text-sm font-bold hover:bg-blue-100 transition-colors'>`n          {icons[link.platform] || link.platform.slice(0,2).toUpperCase()}`n        </a>`n      ))}`n    </div>`n  )`n}"
}

foreach ($name in $components.Keys) {
  $content = $components[$name]
  $path = "app/components/$name.tsx"
  $content | Out-File -FilePath $path -Encoding utf8 -NoNewline
  git add $path
  git commit -m "feat: add $name UI component"
}

Write-Host "Phase 4 done!"
